### ISSUE TITLE
Error: too many ids requested.

### ISSUE THREAD

**Issue by DynamoYT** [thelinmichael/spotify-web-api-node#356]
```
C:\Users\hacke\Desktop\abcd\node_modules\spotify-web-api-node\src\http-manager.js:39
    return new WebapiRegularError(response.body, response.headers, response.statusCode);
           ^

WebapiRegularError: An error occurred while communicating with Spotify's Web API.
Details: too many ids requested.
    at _toError (C:\Users\hacke\Desktop\abcd\node_modules\spotify-web-api-node\src\http-manager.js:39:12)
    at C:\Users\hacke\Desktop\abcd\node_modules\spotify-web-api-node\src\http-manager.js:71:25
    at Request.callback (C:\Users\hacke\Desktop\abcd\node_modules\superagent\lib\node\index.js:905:3)
    at C:\Users\hacke\Desktop\abcd\node_modules\superagent\lib\node\index.js:1127:20
    at IncomingMessage.<anonymous> (C:\Users\hacke\Desktop\abcd\node_modules\superagent\lib\node\parsers\json.js:22:7)
    at Stream.emit (node:events:327:20)
    at Unzip.<anonymous> (C:\Users\hacke\Desktop\abcd\node_modules\superagent\lib\node\unzip.js:53:12)
    at Unzip.emit (node:events:327:20)
    at endReadableNT (node:internal/streams/readable:1289:12)
    at processTicksAndRejections (node:internal/process/task_queues:80:21) {
  body: { error: { status: 400, message: 'too many ids requested' } },
  headers: {
    'content-type': 'application/json; charset=utf-8',
    'cache-control': 'private, max-age=0',
    'x-robots-tag': 'noindex, nofollow',
    'access-control-allow-origin': '*',
    'access-control-allow-headers': 'Accept, App-Platform, Authorization, Content-Type, Origin, Retry-After, Spotify-App-Version, X-Cloud-Trace-Context, client-token, content-access-token',
    'access-control-allow-methods': 'GET, POST, OPTIONS, PUT, DELETE, PATCH',
    'access-control-allow-credentials': 'true',
    'access-control-max-age': '604800',
    'content-encoding': 'gzip',
    'strict-transport-security': 'max-age=31536000',
    'x-content-type-options': 'nosniff',
    date: 'Thu, 14 Jan 2021 15:54:41 GMT',
    server: 'envoy',
    via: 'HTTP/2 edgeproxy, 1.1 google',
    'alt-svc': 'clear',
    connection: 'close',
    'transfer-encoding': 'chunked'
  },
  statusCode: 400
}
```

Playlist URL: https://open.spotify.com/playlist/4rnleEAOdmFAbRcNCgZMpY

**Comment by zaosoula** [comment]
Can you share your code as well, with only the error it's hard to see where the problem is

**Comment by DynamoYT** [comment]
```
   const data = await spotifyApi.getPlaylist("4rnleEAOdmFAbRcNCgZMpY");
    let b = []
    
    let tracks = data.body.tracks.items.map( a => {
    
        b.push(a.track.id)
       
    });
    console.log(b)
    console.log(b.length)
```
It only gives 100 songs id

**Comment by zaosoula** [comment]
The Spotify web API [limit each call to 100 tracks](https://developer.spotify.com/documentation/web-api/reference-beta/#endpoint-get-playlists-tracks) to fetch all tracks you can use a loop

``javascript
async getPlaylistWithTracks(id) {
  const playlist = (await spotifyApi.getPlaylist(id)).body

  // if there is more tracks than the limit (100 by default)
  if (playlist.tracks.total > playlist.tracks.limit) {

    // Divide the total number of track by the limit to get the number of API calls
    for (let i = 1; i < Math.ceil(playlist.tracks.total / playlist.tracks.limit); i++) {

      const trackToAdd = (await spotifyApi.getPlaylistTracks(id, {
        offset: playlist.tracks.limit * i // Offset each call by the limit * the call's index
      })).body;

      // Push the retreived tracks into the array
      trackToAdd.items.forEach((item) => playlist.tracks.items.push(item));
    }
  }

  return playlist
}

const playlist = await getPlaylistWithTracks("4rnleEAOdmFAbRcNCgZMpY");

let tracksIds = playlist.tracks.items.map( item => item.track.id );

console.log(tracksIds);

console.log(tracksIds.length);
``

**Comment by DynamoYT** [comment]
Thank you so much!
