### ISSUE TITLE
No Token Provided

### ISSUE THREAD

**Issue by Takiyo0** [thelinmichael/spotify-web-api-node#362]
I'm sorry if this issue is easy to fix, but i'm stuck and can't figure out what is the problem. It always show 
```
Details: No token provided.
    at _toError (C:\Users\Users\Documents\ChilledChino Assets\ChilledChino\node_modules\spotify-web-api-node\src\http-manager.js:39:12)
    at C:\Users\Users\Documents\ChilledChino Assets\ChilledChino\node_modules\spotify-web-api-node\src\http-manager.js:71:25
    at Request.callback (C:\Users\Users\Documents\ChilledChino Assets\ChilledChino\node_modules\superagent\lib\node\index.js:905:3)
    at C:\Users\Users\Documents\ChilledChino Assets\ChilledChino\node_modules\superagent\lib\node\index.js:1127:20
    at IncomingMessage.<anonymous> (C:\Users\Users\Documents\ChilledChino Assets\ChilledChino\node_modules\superagent\lib\node\parsers\json.js:22:7)
    at Stream.emit (events.js:315:20)
    at Unzip.<anonymous> (C:\Users\Users\Documents\ChilledChino Assets\ChilledChino\node_modules\superagent\lib\node\unzip.js:53:12)
    at Unzip.emit (events.js:315:20)
    at endReadableNT (_stream_readable.js:1327:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  body: { error: { status: 401, message: 'No token provided' } },
  headers: {
    'www-authenticate': 'Bearer realm="spotify"',
    'access-control-allow-origin': '*',
    'access-control-allow-headers': 'Accept, App-Platform, Authorization, Content-Type, Origin, Retry-After, Spotify-App-Version, X-Cloud-Trace-Context, client-token, content-access-token',
    'access-control-allow-methods': 'GET, POST, OPTIONS, PUT, DELETE, PATCH',
    'access-control-allow-credentials': 'true',
    'access-control-max-age': '604800',
    'content-type': 'application/json',
    'content-encoding': 'gzip',
    'strict-transport-security': 'max-age=31536000',
    'x-content-type-options': 'nosniff',
    date: 'Mon, 25 Jan 2021 10:59:07 GMT',
    server: 'envoy',
    via: 'HTTP/2 edgeproxy, 1.1 google',
    'alt-svc': 'clear',
    connection: 'close',
    'transfer-encoding': 'chunked'
  },
  statusCode: 401
}
```

and my code is
```
var SpotifyWebApi = require('spotify-web-api-node');

var spotifyApi = new SpotifyWebApi({
  clientId: 'xxxxxxxxxxxxxx',
  clientSecret: 'xxxxxxxxxxxxxxxx',
redirectUri: 'localhost:3000'
});

spotifyApi.getPlaylist('5ieJqeLJjjI8iJWaxeBLuK')
  .then(function(data) {
    console.log('Some information about this playlist', data.body);
  }, function(err) {
    console.log('Something went wrong!', err);
  });
```
yeah i use the example on readme. I've use client ID and client Secret that is working properly on other module. Is it all about redirectUri or something?

**Comment by thelinmichael** [comment]
Hi @Takiyo0! The error is actually right there - You're not setting the (access) token. 

You may want to use the Client Credentials authentication flow, it's the easiest and doesn't require a redirect URI. However, it can't be used to make requests that requires a users permission. Retrieving a playlist that you already have the URI doesn't require a users permission.

This [example](https://github.com/thelinmichael/spotify-web-api-node/blob/master/examples/access-token-using-client-credentials.js) should help you.

**Comment by Takiyo0** [comment]
oh yes, i see. Thank you for the information ^^
