### ISSUE TITLE
nodejs spotify web api cant authenticate with access_token

### ISSUE THREAD

**Issue by MartinBarker** [thelinmichael/spotify-web-api-node#392]
**[\[My code is on the 'spotifyAPI' branch of this repo\]][1]**
Hello, I am trying to make a nodejs website where somebody can login to their spotify account, and I can make api calls like get their top tracks / get info on an artist / edit playlists etc...

I've been trying to use this npm library: https://github.com/thelinmichael/spotify-web-api-node
And a couple other methods but have yet to successfully do so. The workflow I'm trying to get working looks like this:

1) User goes to http://localhost:3000/login route which will redirect you to spotify login page
2) once user logs in, spotify will redirect them back to http://localhost:3000/callback
The url will look something like this:
```
http://localhost:3000/callback?code=AQC6MROz21231321231231231231231231231231231231231-EXAMPLE-CODE-3212123123123YcBz8VyvtSe#_=_
```
3) nodejs project gets access_code from the redirected url, uses it to authenticate and start making api requests

The problem is with step 3, I can authenticate and get the access_code, but havent been able to make any api requests, on the backend, in my app.js nodejs server file,  I run this function in order to use the spotify api:

```
function useSpotifyApi(access_token){
  var SpotifyWebApi = require('spotify-web-api-node');

  // credentials are optional
  var spotifyApi = new SpotifyWebApi({
  //  clientId: 'zzz',
  //  clientSecret: 'zzz',
    redirectUri: 'http://localhost:3000/callback'
  });

  spotifyApi.setAccessToken(access_token);

  // Get Elvis' albums
  spotifyApi.getArtistAlbums('43ZHCT0cAZBISjO8DG9PnE').then(
    function(data) {
      console.log('Artist albums', data.body);
    },
    function(err) {
      console.error("err=",err);
    }
  );

}
```

But I always get an error saying the token is invalid:

```
err= WebapiRegularError: An error occurred while communicating with Spotify's Web API.
Details: Invalid access token.
    at _toError (C:\Users\marti\Documents\projects\nodejs-express-template\node_modules\spotify-web-api-node\src\http-manager.js:39:12)
    at C:\Users\marti\Documents\projects\nodejs-express-template\node_modules\spotify-web-api-node\src\http-manager.js:71:25
    at Request.callback (C:\Users\marti\Documents\projects\nodejs-express-template\node_modules\superagent\lib\node\index.js:905:3)
    at C:\Users\marti\Documents\projects\nodejs-express-template\node_modules\superagent\lib\node\index.js:1127:20
    at IncomingMessage.<anonymous> (C:\Users\marti\Documents\projects\nodejs-express-template\node_modules\superagent\lib\node\parsers\json.js:22:7)
    at Stream.emit (events.js:315:20)
    at Unzip.<anonymous> (C:\Users\marti\Documents\projects\nodejs-express-template\node_modules\superagent\lib\node\unzip.js:53:12)
    at Unzip.emit (events.js:327:22)
    at endReadableNT (_stream_readable.js:1220:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  body: { error: { status: 401, message: 'Invalid access token' } },
  headers: {
    'www-authenticate': 'Bearer realm="spotify", error="invalid_token", error_description="Invalid access token"',
    'access-control-allow-origin': '*',
    'access-control-allow-headers': 'Accept, App-Platform, Authorization, Content-Type, Origin, Retry-After, Spotify-App-Version, X-Cloud-Trace-Context, client-token, content-access-token',
    'access-control-allow-methods': 'GET, POST, OPTIONS, PUT, DELETE, PATCH',
    'access-control-allow-credentials': 'true',
    'access-control-max-age': '604800',
    'content-type': 'application/json',
    'content-encoding': 'gzip',
    'strict-transport-security': 'max-age=31536000',
    'x-content-type-options': 'nosniff',
    date: 'Wed, 26 May 2021 01:42:45 GMT',
    server: 'envoy',
    via: 'HTTP/2 edgeproxy, 1.1 google',
    'alt-svc': 'clear',
    connection: 'close',
    'transfer-encoding': 'chunked'
  },
  statusCode: 401
}
```

Am I doing something wrong? how can i authenticate with the spotify web api using nodejs/express and make api requests ?

  [1]: https://github.com/MartinBarker/nodejs-express-template/tree/spotifyAPI

**Comment by vettorazi** [comment]
Hi Martin.
I'm glad you fixed your code and closed this thread.
Next time,  how about mentioning how you fixed?

**Comment by olso** [comment]
@vettorazi use `api.authorizationCodeGrant('THAT_LONG_CODE')`
