### ISSUE TITLE
getting webapi problem 

### ISSUE THREAD

**Issue by sdetweil** [thelinmichael/spotify-web-api-node#422]
error 
```
Something went wrong! WebapiRegularError: An error occurred while communicating with Spotify's Web API.
Details: Not found
    at _toError (/home/sam/ss/node_modules/spotify-web-api-node/src/http-manager.js:39:12)
    at /home/sam/ss/node_modules/spotify-web-api-node/src/http-manager.js:71:25
    at Request.callback (/home/sam/ss/node_modules/superagent/lib/node/index.js:905:3)
    at /home/sam/ss/node_modules/superagent/lib/node/index.js:1127:20
    at IncomingMessage.<anonymous> (/home/sam/ss/node_modules/superagent/lib/node/parsers/json.js:22:7)
    at Stream.emit (events.js:315:20)
    at Stream.EventEmitter.emit (domain.js:483:12)
    at Unzip.<anonymous> (/home/sam/ss/node_modules/superagent/lib/node/unzip.js:53:12)
    at Unzip.emit (events.js:327:22)
    at Unzip.EventEmitter.emit (domain.js:483:12)
    at endReadableNT (_stream_readable.js:1220:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
```
transfer, getplaystatus

stack trace above from 
```
return spotify.transferMyPlayback([id]).then(
```

both fail the same...

get list of devices works. 

on v 5.0.2

my code was last 'tested' on may 13, 2021

**Comment by sdetweil** [comment]
after using the spotify app to start play, then it works again.   

so its some long time idle state
