### ISSUE TITLE
web-api error since today. But why?

### ISSUE THREAD

**Issue by DenisMtfl** [thelinmichael/spotify-web-api-node#426]
18 Nov 07:59:47 - [info] [debug:f5fa56e4.cdc208] WebapiError: [object Object] at _toError (/opt/iobroker/iobroker-data/node-red/node_modules/spotify-web-api-node/src/http-manager.js:47:10) at fn (/opt/iobroker/iobroker-data/node-red/node_modules/spotify-web-api-node/src/http-manager.js:71:25) at Request.callback (/opt/iobroker/iobroker-data/node-red/node_modules/superagent/src/node/index.js:902:3) at IncomingMessage.<anonymous> (/opt/iobroker/iobroker-data/node-red/node_modules/superagent/src/node/index.js:1130:18) at Stream.emit (events.js:314:20) at Unzip.<anonymous> (/opt/iobroker/iobroker-data/node-red/node_modules/superagent/src/node/unzip.js:54:12) at Unzip.emit (events.js:326:22) at endReadableNT (_stream_readable.js:1241:12) at processTicksAndRejections (internal/process/task_queues.js:84:21) { body: {}, headers: { 'cache-control': 'private, max-age=0', 'retry-after': '13749', 'access-control-allow-origin': '*', 'access-control-allow-headers': 'Accept, App-Platform, Authorization, Content-Type, Origin, Retry-After, Spotify-App-Version, X-Cloud-Trace-Context, client-token, content-access-token', 'access-control-allow-methods': 'GET, POST, OPTIONS, PUT, DELETE, PATCH', 'access-control-allow-credentials': 'true', 'access-control-max-age': '604800', 'content-encoding': 'gzip', 'strict-transport-security': 'max-age=31536000', 'x-content-type-options': 'nosniff', date: 'Thu, 18 Nov 2021 06:59:47 GMT', server: 'envoy', via: 'HTTP/2 edgeproxy, 1.1 google', 'alt-svc': 'clear', connection: 'close', 'transfer-encoding': 'chunked' }, statusCode: 429}

**Comment by kevinguebert** [comment]
Status Code 429 usually means ["Too Many Requests"](https://httpstatuses.com/429). If that status code is coming from Spotify then you are probably being rate-limited
