### ISSUE TITLE
[URGENT] Server Error with Code 500 

### ISSUE THREAD

**Issue by Ayush-0801** [thelinmichael/spotify-web-api-node#459]
This my code snippet
```
  var intervalID=setInterval(async ()=> {
    
    var me, trk1, trk2;
    me = await spotifyApi.getAudioFeaturesForTracks(trackIdCollection[i])
    trk1 = await spotifyApi.getTracks(trackIdCollection[i].slice(0, trackIdCollection[i].length/2));
    trk2 = await spotifyApi.getTracks(trackIdCollection[i].slice(trackIdCollection[i].length/2, trackIdCollection[i].length));
 }, 1000);
```

And this is my error message
```
  return new WebapiRegularError(response.body, response.headers, response.statusCode);
           ^

WebapiRegularError: An error occurred while communicating with Spotify's Web API.
Details: Server error..
    at _toError (/Users/ayush01misra/Desktop/homeware/Queue Player/Development/queuePlayer-Database/node_modules/spotify-web-api-node/src/http-manager.js:39:12)
    at /Users/ayush01misra/Desktop/homeware/Queue Player/Development/queuePlayer-Database/node_modules/spotify-web-api-node/src/http-manager.js:71:25
    at Request.callback (/Users/ayush01misra/Desktop/homeware/Queue Player/Development/queuePlayer-Database/node_modules/spotify-web-api-node/node_modules/superagent/lib/node/index.js:905:3)
    at /Users/ayush01misra/Desktop/homeware/Queue Player/Development/queuePlayer-Database/node_modules/spotify-web-api-node/node_modules/superagent/lib/node/index.js:1127:20
    at IncomingMessage.<anonymous> (/Users/ayush01misra/Desktop/homeware/Queue Player/Development/queuePlayer-Database/node_modules/spotify-web-api-node/node_modules/superagent/lib/node/parsers/json.js:22:7)
    at Stream.emit (node:events:390:28)
    at Unzip.<anonymous> (/Users/ayush01misra/Desktop/homeware/Queue Player/Development/queuePlayer-Database/node_modules/spotify-web-api-node/node_modules/superagent/lib/node/unzip.js:53:12)
    at Unzip.emit (node:events:390:28)
    at endReadableNT (node:internal/streams/readable:1343:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  body: { error: { status: 500, message: 'Server error.' } },
  headers: {
    'content-type': 'application/json; charset=utf-8',
    'cache-control': 'private, max-age=0',
    'x-robots-tag': 'noindex, nofollow',
    'access-control-allow-origin': '*',
    'access-control-allow-headers': 'Accept, App-Platform, Authorization, Content-Type, Origin, Retry-After, Spotify-App-Version, X-Cloud-Trace-Context, client-token, content-access-token',
    'access-control-allow-methods': 'GET, POST, OPTIONS, PUT, DELETE, PATCH',
    'access-control-allow-credentials': 'true',
    'access-control-max-age': '604800',
    'content-encoding': 'gzip',
    'strict-transport-security': 'max-age=31536000',
    'x-content-type-options': 'nosniff',
    date: 'Mon, 20 Jun 2022 22:57:02 GMT',
    server: 'envoy',
    via: 'HTTP/2 edgeproxy, 1.1 google',
    'alt-svc': 'h3=":443"; ma=2592000,h3-29=":443"; ma=2592000',
    connection: 'close',
    'transfer-encoding': 'chunked'
  },
  statusCode: 500
}
```

**Comment by IsRoninReal** [comment]
i have that too when i try get somethings from api its just says 500 internal server error
